### ISSUE TITLE
[Bug] Does Not work.

### ISSUE THREAD

**Issue by yodaluca23** [nfriedly/node-unblocker#200] opened 2022-04-26 18:36 UTC
I get this error when typing into the box on the website...

404: NOT_FOUND
Code: NOT_FOUND
ID: cle1::2ll66-1650660303423-30434533a769

I deployed the [Nodeunblocker.com](https://github.com/nfriedly/nodeunblocker.com) Repository to vercel onto my site ([climatechange123.tk](climatechange123.tk)) but I get the above error...

**Comment by nfriedly** [comment] 2022-04-26 18:54
I'm really not sure. Maybe Vercel is static hosting only? Or maybe you only deployed the index page?

At any rate, I'm pretty confident that it's not a bug in node-unblocker, so I'm going to close this ticket. 

If you figure out how to make it work, please open a PR to the nodeunblocker.com repo adding instructions to the readme.

**Closed by nfriedly** 2022-04-26 18:54 UTC

**Comment by yodaluca23** [comment] 2022-04-26 19:24
How would I know if Vercel only allows static pages or not? and if they don't then do you know of any free service like vercel that lets me host this proxy on my own URL (climatechange123.tk) and not like Heroku where proxies are not being against their TOS, and they instantly ban you if you deploy this.. so this is what I need:

1. Completely free
2. Allow me to use my own URL
3. Allow proxies according to their TOS
4. work with CloudFlare

**Comment by nfriedly** [comment] 2022-04-26 20:12
I really don't know; I gave up on trying to host this thing years ago, because I just got banned everywhere I went. Your best option might just be a computer in your home. Even something cheap like a raspberry pi or a 10-year-old PC would work.

**Comment by yodaluca23** [comment] 2022-04-27 19:51
Is there a simple guide somewhere for setting it up on a raspberry pi? (I looked through the readme and found nothing) also doing that could I access it off my home network and on my own URL  and multiple custom URLS? with Cloudflare too?

**Comment by nfriedly** [comment] 2022-04-27 20:16
Apparently Raspberry PI OS now includes an older version of node.js, but it's not so old that you can't use it. So you can skip right to step 2 here: https://github.com/nfriedly/nodeunblocker.com#running-the-website-on-your-computer

If you get through that, it will be working locally. 

To expose it to the internet at large, you need to 
- figure out how to enable port forwarding in your router
- set up something like no-ip.com to get a url that will update when your IP changes
  - or just use your IP - they don't usually change that often. Go to somewhere like https://whatsmyip.com/ to see your current IP
- set up cloudflare to point to either your IP or the url you set up in the previous step

That's the gist of it, but I can't really go into much more specifics beyond that

**Comment by yodaluca23** [comment] 2022-04-28 23:52
Would [this ](https://smile.amazon.com/USB-HUB-HAT-Board-Compatible/dp/B07X1BH5FN/ref=sr_1_3?keywords=raspberry+pi+zero+ethernet)Rasberry PI work?

**Comment by nfriedly** [comment] 2022-04-29 01:22
The initial link wouldn't, it was an add-on board (a "hat"), but the second one for a raspy pi 4 would be fine. You'd more than just the board, though - you also need a micro SD card, power supply, keyboard, mouse, screen (a TV will work if necessary), and micro HDMI adapter / cable.

Also, unless your microSD comes pre-loaded with NOOBS, you'd need another computer to set that up initially.

There's a bunch of places that sell kits with everything, including the pre-loaded microSD.

(There's also the Raspberry Pi 400, which is just a raspberry pi 4 inside of a keyboard, so you don't need another keyboard for that model.)

**Comment by yodaluca23** [comment] 2022-04-29 01:25
I would only need those to get it set up though, right? Then I could just keep it plugged into power and be good?

**Comment by nfriedly** [comment] 2022-04-29 01:40
Yeah, for the most part. You'll probably need to log in occasionally for maintenance, but you can set it up to enable remote control via either ssh (command line only) or vnc (full desktop) for that.

**Comment by yodaluca23** [comment] 2022-05-04 01:04
> I really don't know; I gave up on trying to host this thing years ago, because I just got banned everywhere I went. Your best option might just be a computer in your home. Even something cheap like a raspberry pi or a 10-year-old PC would work.

Found One! (Putting the info out their) [Openode ](https://www.openode.io/)checks all the boxes! I can host it on my URL for free it works fine with Cloudflare and I'm fairly certain that it is allowed in their TOS to have proxy sites!
