### ISSUE TITLE
roblox

### ISSUE THREAD

**Issue by gabetheswe** [nfriedly/node-unblocker#156] opened 2021-01-16 22:53 UTC
im on a school computer and i cant play roblox

**Comment by loucs2049** [comment] 2021-02-10 19:11
I am on school computer and i can get on the website but i cannot log into my account because it keep on loading....

**Comment by nfriedly** [comment] 2021-02-10 19:56
I know that roblox doesn't work; it will likely take a significant amount of effort to get it to work, and I don't have the time for that right now. If either of you want to take a stab at it, feel free.

Closing as a duplicate of #142

**Closed by nfriedly** 2021-02-10 19:56 UTC
